# Generated by Django 5.2.9 on 2026-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enguser',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('teacher', '任课教师'), ('expert', '认证专家')], default='teacher', max_length=20, verbose_name='角色'),
        ),
    ]
