# Generated by Django 5.2.9 on 2026-04-11 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='排序值')),
            ],
            options={
                'verbose_name': '材料分类',
                'verbose_name_plural': '材料分类',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='课程编号')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('credit', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='学分')),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '选修')], default='required', max_length=20, verbose_name='课程类型')),
                ('term', models.CharField(blank=True, max_length=30, null=True, verbose_name='开课学期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseAttainmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=30, verbose_name='学年')),
                ('term', models.CharField(max_length=30, verbose_name='学期')),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='目标值')),
                ('actual_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='实际达成值')),
                ('conclusion', models.CharField(blank=True, max_length=200, null=True, verbose_name='达成结论')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attainment_records', to='accreditation.course', verbose_name='课程')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '课程达成度记录',
                'verbose_name_plural': '课程达成度记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='目标编号')),
                ('content', models.TextField(verbose_name='目标内容')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='排序值')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accreditation.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程目标',
                'verbose_name_plural': '课程目标',
                'ordering': ['course__code', 'sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容说明')),
                ('version', models.CharField(default='2024版', max_length=50, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '毕业要求',
                'verbose_name_plural': '毕业要求',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='材料标题')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='上传文件')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已通过'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='审核状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accreditation.course', verbose_name='所属课程')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='accreditation.materialcategory', verbose_name='材料分类')),
            ],
            options={
                'verbose_name': '课程材料',
                'verbose_name_plural': '课程材料',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='RequirementIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='指标点编号')),
                ('content', models.TextField(verbose_name='指标点内容')),
                ('sort', models.PositiveIntegerField(default=1, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('graduation_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='accreditation.graduationrequirement', verbose_name='所属毕业要求')),
            ],
            options={
                'verbose_name': '指标点',
                'verbose_name_plural': '指标点',
                'ordering': ['graduation_requirement__code', 'sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalIndicatorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_relations', to='accreditation.coursegoal', verbose_name='课程目标')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_relations', to='accreditation.requirementindicator', verbose_name='指标点')),
            ],
            options={
                'verbose_name': '目标支撑关系',
                'verbose_name_plural': '目标支撑关系',
                'ordering': ['goal__course__code', 'goal__sort', 'indicator__code'],
            },
        ),
        migrations.CreateModel(
            name='CourseIndicatorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_level', models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], default='middle', max_length=20, verbose_name='支撑强度')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_relations', to='accreditation.course', verbose_name='课程')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relations', to='accreditation.requirementindicator', verbose_name='指标点')),
            ],
            options={
                'verbose_name': '课程支撑关系',
                'verbose_name_plural': '课程支撑关系',
                'ordering': ['course__code', 'indicator__code'],
            },
        ),
    ]
