# Generated by Django 5.2.9 on 2026-04-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('source', models.CharField(choices=[('attainment', '达成分析'), ('material', '材料检查'), ('course', '课程评估'), ('other', '其他')], default='other', max_length=30, verbose_name='问题来源')),
                ('problem_description', models.TextField(verbose_name='问题描述')),
                ('improvement_measure', models.TextField(verbose_name='整改措施')),
                ('planned_finish_date', models.DateField(blank=True, null=True, verbose_name='计划完成时间')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度(%)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='整改状态')),
                ('effect_evaluation', models.TextField(blank=True, null=True, verbose_name='效果评价')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accreditation.course', verbose_name='关联课程')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_improvement_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_items', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '持续改进',
                'verbose_name_plural': '持续改进',
                'ordering': ['status', 'planned_finish_date', '-create_time'],
            },
        ),
    ]
