# Generated by Django 5.2.9 on 2026-04-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0002_continuousimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousimprovement',
            name='attainment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_items', to='accreditation.courseattainmentrecord', verbose_name='关联达成度记录'),
        ),
    ]
