# Generated by Django 5.2.9 on 2026-04-15 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0003_continuousimprovement_attainment_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100, verbose_name='学院')),
                ('major_name', models.CharField(max_length=100, verbose_name='专业')),
                ('plan_year', models.PositiveIntegerField(verbose_name='年份')),
                ('plan_file', models.FileField(blank=True, null=True, upload_to='training_plans/', verbose_name='培养方案文件')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '培养方案',
                'verbose_name_plural': '培养方案',
                'ordering': ['-plan_year', 'college_name', 'major_name', 'id'],
                'unique_together': {('college_name', 'major_name', 'plan_year')},
            },
        ),
    ]
