# Generated by Django 5.2.9 on 2026-04-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditation', '0004_trainingplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_no', models.CharField(max_length=30, unique=True, verbose_name='学号')),
                ('college_name', models.CharField(max_length=100, verbose_name='学院')),
                ('major_name', models.CharField(max_length=100, verbose_name='专业')),
                ('grade_name', models.CharField(max_length=30, verbose_name='年级')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('status', models.CharField(choices=[('studying', '在读'), ('suspended', '休学'), ('graduated', '毕业')], default='studying', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['student_no', 'id'],
            },
        ),
    ]
